### ISSUE TITLE
Sample weapons cause errors

### ISSUE THREAD

**Issue by func-boncey** [reepblue/SourceSDK2010#6]
Hi! I'm attempting to make a mod using this base, and I'm attempting to use the sample weapons included, or at least I believe they are sample weapons, smg1, pistol, crowbar and shotgun. 

I included these into the project and when first compiling these I got an error saying that "basesdkcombatweapon_shared.h could not be found", so I happily gave it a path to the one in shared and it's throwing me many undefined symbol errors which can be read here: http://pastebin.com/rZRBNLjk

After that, I removed basesdkcombatweapon and compiled, there were a lot less errors, I fixed these up by adding the missing variables to the class and such, but I believe that may have done more damage than good.
I have also attempted to fix up these by making them more like weapon_cubemap, I got it to compile but now it just crashes.

Sorry if I am doing something silly, I'm quite new to developing Source mods and the structure to it.

Thanks
-Boncey

**Comment by reepblue** [comment]
Oh hey,

Yeah the weapon system is not really perfect when it comes to "easy to install" (really should look into a solution builder....)

Anyway, here are things you can try. I recommend starting from  scratch.

1) Make sure you installed the project right: http://sourceenginedocs.blogspot.com/

2) Add ".\weapons" to the "Additional Include Directories" under both Client and Server. (Right Click on the project -> Configuration Properties -> C\C++)

3) Add all the cpp/h files of three weapon folders. ...client/template/weapons gets added in the client project, ...server/template/weapons gets added in the server project, and you add the ...shared/template/weapons in both projects. 

4) Delete weapon_parse_default from BOTH projects. Sometimes I forget this step.

You also need weapon view models/world models. I'm not 100% sure the HL2 view models will crash the game, but I know the world models will. I think HL2 SFM will have compatible models. If you're project can load the default map (with no weapons) after adding the weapon files, you should be set. Then you can try giving yourself weapons via console.

**Comment by func-boncey** [comment]
Yeah, I heard about loading the models in SFM, that was my plan. I'll try all this out. Thanks for the very fast response. ^.^

**Comment by func-boncey** [comment]
Yep! Working. You're a miracle worker. Thanks for your amazing work!
