### ISSUE TITLE
NPCs

### ISSUE THREAD

**Issue by SleepyAkubi** [reepblue/SourceSDK2010#7]
Hi! I'm attempting to port over NPCs but I'm having some issues locating what the new classes types etc are for this engine branch, is there a guide or a sample NPC you could add that would make this easier.

Thanks
-Boncey

**Comment by reepblue** [comment]
I have nit really tried npcs but the base class for npcs should be there. 

I do have a cpp file somewhere where it's a simplified version of the L4D infected on my other PC. Until I manage to find that, again I would look at the HL2 stuff, and the ASW aliens and compare how the two branches handle npcs. Some strings might be different. I'll keep you posted as I should have an npc example.

**Comment by func-boncey** [comment]
Ok, thanks for the fast response again. :smile:

**Comment by func-boncey** [comment]
It's been a little while, I'm sorry to distrub you, but do you have that copy of the NPC example?

**Comment by reepblue** [comment]
Yeah, sorry been busy with other things. I'll take a look right now and report back in the morning.

**Comment by func-boncey** [comment]
Thanks :smile:

**Comment by reepblue** [comment]
I have not tested this with this branch, but I managed to find a basic npc cpp. If you have L4D installed, you should know what to do. 

https://dl.dropboxusercontent.com/u/16218991/Requests/npc_infected.cpp

**Comment by func-boncey** [comment]
I'll give it a try, thanks alot :smiley:
